---
# Lesson 5 Lab: Using Ansible Vault
#   Create a playbook that creates a user. The user as well as the password should come from a variable.
#   Define both in separate include files.
#   Make sure the password is encrypted with vault, whereas the username is not encrypted with vault.
#   Verify it works.

- name: lab05
  hosts: ansible2
  gather_facts: no
  vars_files:
    - ./var_files/username01
    - ./var_files/password01
  

  tasks:
    - name: creating a new user
      user:
        name: test_user
        state: present

    - name: setting a password #creating a password through the shell module allows for setting an encrypted password without manually encrypting it
      shell: "echo {{pass_01}} | passwd --stdin {{username}}"
      register: result
    
    - name: verification
      debug:
        var: result